howx/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('users.urls')),
    path('', include('survey.urls')),
]

survey/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views
from . import survey, question
from .submit_survey import submit_survey

urlpatterns = [
    path('survey/<slug:survey_name>/<int:pk>/update/',
         login_required(question.QuestionUpdate.as_view()), name='question_update'),
    path('survey/<slug:survey_name>/new/', login_required(question.QuestionCreate.as_view()), name='question_create'),
    path('survey/first/', survey.SurveyView.as_view(), name='survey_first'),  # Show the first (usually the only) survey
    path('survey/<slug:slug>/edit/', login_required(survey.SurveyUpdate.as_view()), name='survey_update'),
    path('survey/<slug:survey_name>/submit/', submit_survey, name='survey_submit'),
    path('survey/<slug:survey_name>/', survey.SurveyView.as_view(), name='survey_detail'),
    path('surveys/', survey.SurveyList.as_view(), name='survey_list'),
    path('create/', login_required(survey.SurveyCreate.as_view()), name='survey_create'),
    path('', views.home, name='home'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import UserList, UserDetail, UserUpdate, UserDelete


urlpatterns = [
    url(r'^user/(?P<slug>[\w]+)/edit/$', login_required(UserUpdate.as_view()), name='user_update'),
    url(r'^user/(?P<slug>[\w]+)/delete/$', login_required(UserDelete.as_view()), name='user_delete'),
    url(r'^user/(?P<slug>[\w]+)/$', UserDetail.as_view(), name='user_detail'),
    url(r'^users/$', login_required(UserList.as_view()), name='user_list'),
    url(r'^accounts/profile/$', login_required(UserDetail.as_view()), name='profile'),
]

survey/models.py
from django.db import models
from django.contrib import auth
from django.utils.translation import ugettext_lazy


class Survey(models.Model):
    """ Set of questions """
    name = models.SlugField(max_length=200, unique=True, verbose_name=ugettext_lazy('name'),
                            help_text=ugettext_lazy('Must be unique. Used in URL.'))
    title = models.CharField(max_length=250)
    description = models.TextField(default='', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(auth.get_user_model(), on_delete=models.CASCADE, null=True, default=None, blank=True)
    edited = models.DateTimeField(auto_now=True)

    def can_edit(self, user):
        if user == self.creator:
            return True

        return False

    @property
    def questions(self):
        return Question.objects.filter(survey=self).order_by('order', 'title')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['title']


class Question(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    order = models.IntegerField(default=0)
    title = models.CharField(max_length=250)
    description = models.TextField(default='', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    edited = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}:{}:{}'.format(self.survey.name, self.order, self.title)


class Reference(models.Model):
    """ Set of reference answers to which user answers will be compared to """
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    name = models.SlugField(max_length=200, unique=True)
    title = models.CharField(max_length=250)
    description = models.TextField(default='', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    edited = models.DateTimeField(auto_now=True)

    def feedback(self, score):
        """ Find feedback corresponding to given score """
        feedbacks = Feedback.objects.filter(reference=self)
        exact = feedbacks.filter(exact_score=score)
        if exact.first():
            return exact.first()

        feedbacks = feedbacks.filter(exact_score=None)
        if score == 0:
            feedbacks = feedbacks.filter(min_score__lte=score)
        else:
            feedbacks = feedbacks.filter(min_score__lt=score)

        feedbacks = feedbacks.filter(max_score__gte=score)
        return feedbacks.first()

    def __str__(self):
        return self.name


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    reference = models.ForeignKey(Reference, on_delete=models.CASCADE,
                                  null=True, blank=True, default=None)
    # user = models.ForeignKey(auth.get_user_model(), on_delete=models.CASCADE)
    value = models.IntegerField(default=0)

    def __str__(self):
        return '{}:{}'.format(self.question.title, self.value)


class Feedback(models.Model):
    """ Give a little feedback based on score """
    reference = models.ForeignKey(Reference, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    description = models.TextField(default='', blank=True)
    exact_score = models.FloatField(null=True, blank=True, default=None)
    min_score = models.FloatField(default=0.0)
    max_score = models.FloatField(default=100.0)

    def __str__(self):
        if self.exact_score:
            return '{}:{} == {}'.format(self.reference.name, self.title, self.exact_score)
        else:
            return '{}:{}:from {} to {}'.format(self.reference.name, self.title, self.min_score, self.max_score)

    class Meta:
        ordering = ['min_score']

users/models.py
from django.db import models

# Create your models here.

questionnaire/views.py
from django.views.generic import TemplateView
# from .upload import UploadForm


class HomeView(TemplateView):
    template_name = 'questionnaire/home.html'

survey/views.py
# from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Survey


def home(request):
    # surveys = Survey.objects.all()
    if Survey.objects.count() == 1:
        return HttpResponseRedirect(reverse('survey_detail', args=[Survey.objects.first().name]))
    else:
        return HttpResponseRedirect(reverse('survey_list'))

users/views.py
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import UpdateView, DeleteView
from django.http import Http404
from django.contrib import auth
from django.shortcuts import get_object_or_404


def can_edit_user(logged_user, target_user):
    """ Is logged in user allowed to edit target user """
    if logged_user == target_user:
        return True
    if logged_user.is_staff:
        return True
    return False


class UserList(ListView):
    model = auth.get_user_model()

    def get_context_data(self, **kwargs):
        context = super(UserList, self).get_context_data(**kwargs)
        context['messages'] = self.request.GET.get('message', '')
        return context


class UserDetail(DetailView):
    template_name = 'auth/profile.html'
    context_object_name = 'target_user'

    def get_object(self, queryset=None):
        target_username = self.kwargs.get('slug', '')
        if target_username:
            # return auth.models.User.objects.get(username=target_username)
            target_user = get_object_or_404(auth.get_user_model(), username=target_username)
            return target_user

        return auth.get_user(self.request)


class UserUpdate(UpdateView):
    model = auth.get_user_model()
    slug_field = 'username'
    fields = ['first_name', 'last_name']

    def get_object(self):
        target_user = super(UserUpdate, self).get_object()
        if can_edit_user(logged_user=self.request.user, target_user=target_user):
            return target_user

        # Todo: Smarter way to handle this
        raise Http404

    def get_context_data(self, **kwargs):
        context = super(UserUpdate, self).get_context_data(**kwargs)
        context['message'] = self.request.GET.get('message', '')
        return context

    def get_success_url(self):
        if self.object:
            return reverse_lazy('user_detail', args=[self.object.username])
        else:
            return reverse('user_list')


class UserDelete(DeleteView):
    slug_field = 'username'
    model = auth.models.User
    success_url = reverse_lazy('home')

    def get_object(self):
        target_user = super(UserDelete, self).get_object()
        if can_edit_user(logged_user=self.request.user, target_user=target_user):
            return target_user

        # Todo: Smarter way to handle this
        raise Http404

    def render_to_response(self, context, **response_kwargs):
        return super(UserDelete, self).render_to_response(context, **response_kwargs)

questionnaire/templates/questionnaire/home.html
{% extends "questionnaire/base.html" %}

{% block title %}How X are you?{% endblock %}
{% block content %}
    <h1> How X are you? </h1>
{% endblock content %}

survey/templates/survey/base.html
<!DOCTYPE html>

{% load i18n %}

<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="/static/png/jln-favicon.png" />
    <title> {% block title %}HowX{% endblock %} </title>
  </head>
  <body>
{% if display != 'fs' and not format %}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'home' %}"></a>
      <div class="collapse navbar-collapse" id="commonNavbar">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}"> {% trans 'Home' %} </a>
          </li>
        </ul>
        <ul class="nav navbar-nav ml-auto">
  {% if user.is_authenticated %}
    {% if user.is_staff %}
          <li class="nav-item">
            <a class="nav-link" id="navbar_users" href="/admin/"> {% trans 'Admin' %} </a>
          </li>
    {% endif %}
          <li class="nav-item">
            <a class="nav-link" id="navbar_users" href="{% url 'account_logout' %}"> {% trans 'Logout' %} </a>
          </li>
  {% else %}
          <li class="nav-item">
            <a class="nav-link" id="navbar_users" href="{% url 'account_login' %}"> {% trans 'Login' %} </a>
          </li>
  {% endif %}
        </ul>
      </div>
    </nav>
{% endif %}
{% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert"> {{ message.tags }}: {{ message }} </div>
{% endfor %}
    <div class="container-fluid">
{% block content %}{% endblock %}
    </div>
  </body>
</html>

survey/templates/survey/home.html
{% extends "survey/base.html" %}

{% block title %}How X are you?{% endblock %}
{% block content %}
    <h1> How X are you? </h1>
{% endblock content %}

survey/templates/survey/question_form.html
{% extends "survey/base.html" %}
{% load i18n %}

{% block content %}

<h1> {{ survey.title }} </h1>

{% if question %}
<form action="{% url 'question_update' question.survey.name question.id %}" method="post">
{% else %}
<h1> {% trans "Create new question" %} </h1>
<form action="{% url 'question_create' survey.name %}" method="post">
{% endif %}
{% csrf_token %}

<table class="table">

  <tr>
    <th> <label for="id_title">{% trans 'Question' %}</label></th>
    <td> <input type="text" name="title" value="{{ question.title }}" required maxlength="250" size="100" id="id_title" /></td>
  </tr>
  <tr>
    <th><label for="id_description">{% trans 'Description' %}:</label></th>
    <td><textarea name="description" rows="10" cols="100" id="id_description"></textarea></td>
  </tr>

{% trans "Save" as save_txt %}
  <tr> <td colspan="2"> <input type="submit" class="btn btn-primary" value="{{ save_txt }}"> </td> </tr>
  <tr> <td colspan="2"> <a href="{% url 'survey_detail' survey.name %}"> {% trans "Back" %} </a> </td> </tr>

</table>

</form>

{% endblock %}

survey/templates/survey/result.html
{% extends "survey/base.html" %}
{% load i18n %}

{% block title %}{{ survey.title }}{% endblock %}
{% block content %}

{% if not survey %}
  {% trans 'No survey' %}
{% else %}

<br/>
<h1 class="text-center"> {% trans 'You are' %} {{ npct|floatformat:0 }} % {{ reference.title }}</h1>

{% if feedback.title %}
<h2 class="text-center"> {{ feedback.title }} </h2>
{% endif %}

{% if feedback.description %}
<h3 class="text-center"> {{ feedback.description }} </h3>
{% endif %}

{% if reference.description %}
<div> {{ reference.description|safe }} </div>
{% endif %}

<h3> {% trans 'Score' %} </h3>
<table class="table">
  <thead>
    <tr>
      <th> {% trans 'Question' %} </th>
      <th class="text-right"> {% trans 'Points' %} </th>
      <!-- <th class="text-right"> {% trans 'NPoints' %} </th> -->
    </tr>
  </thead>
  <tbody>
{% for answer in answers %}
    <tr>
      <td>{{ answer.question.title }}</td>
    {% comment %}
      <td class="text-right {% if answer.points < 0 %}table-danger{% elif answer.points > 0 %}table-success{% endif %}">
        {{ answer.points }}
      </td> #}
    {% endcomment %}
      <td class="text-right {% if answer.points < 0 %}table-danger{% elif answer.points > 0 %}table-success{% endif %}">
        {{ answer.npoints }}
      </td>
    </tr>
{% endfor %}
    <tr>
      <th> {% trans 'Total' %} </th>
      <!-- <th class="text-right"> {{ score }} / {{ max_score }} ({{ pct|floatformat:0 }} %)</th> -->
      <th class="text-right"> {{ nscore }} / {{ nmax_score }} ({{ npct|floatformat:0 }} %) </th>
    </tr>
  </tbody>
</table>
<div><a href="{% url 'survey_detail' survey.name %}">{% trans 'Back' %}</div>

{% endif %}
{% endblock content %}

survey/templates/survey/survey.html
{% extends "survey/base.html" %}
{% load i18n %}

{% block title %}{{ survey.title }}{% endblock %}
{% block content %}
<br/>
{% if not survey %}
  {% trans 'No survey' %}
{% else %}

<h1 class="text-center"> {{ survey.title }} </h1>
<p class="text-center"> {{ survey.description|safe }} </p>

{% if can_edit %}
<p>
  <a class="btn btn-primary" href="{% url 'survey_update' survey.name %}">
    {% trans 'Edit' %}
  </a>
  <a class="btn btn-primary" href="{% url 'question_create' survey.name %}">
    {% trans 'New question' %}
  </a>
</p>
{% endif %}

<form action="{% url 'survey_submit' survey.name %}" method="post">
{% csrf_token %}
<table class="table">
  <thead>
    <tr>
      <th> {% trans 'Question' %} </th>
      <th> {% trans 'Definitely yes' %} </th>
      <th> {% trans 'Maybe yes' %} </th>
      <th> {% trans 'Dunno' %} </th>
      <th> {% trans 'Maybe no' %} </th>
      <th> {% trans 'Definitely no' %} </th>
    </tr>
  </thead>
  <tbody>
{% for question in survey.questions %}
    <tr>
      <td title="{{ question.description|striptags }}">{{ question.title }}</td>
      <td class="text-center"> <input type="radio" name="q-{{ question.id }}" value="2"> </td>
      <td class="text-center"> <input type="radio" name="q-{{ question.id }}" value="1"> </td>
      <td class="text-center"> <input type="radio" name="q-{{ question.id }}" value="0" checked="true"> </td>
      <td class="text-center"> <input type="radio" name="q-{{ question.id }}" value="-1"> </td>
      <td class="text-center"> <input type="radio" name="q-{{ question.id }}" value="-2"> </td>
    {% if can_edit %}
      <td> <a class="btn btn-primary btn-sm" href="{% url 'question_update' survey.name question.id %}">Edit</a></td>
    {% endif %}
    </tr>
{% endfor %}
  </tbody>
</table>
{% trans "Submit" as save_txt %}
<div><input type="submit" class="btn btn-primary" value="{{ save_txt }}"></div>
</form>
{% endif %}
{% endblock content %}

survey/templates/survey/survey_form.html
{% extends "survey/base.html" %}
{% load i18n %}

{% block content %}

{% if survey %}
<h1> {{ survey.title }} </h1>
<form action="{% url 'survey_update' survey.name %}" method="post">
{% else %}
<h1> {% trans "Create new survey" %} </h1>
<form action="{% url 'survey_create' %}" method="post">
{% endif %}
{% csrf_token %}

<table class="table">

{{ form.as_table }}

    {% trans "Save" as save_txt %}
    <tr> <td colspan="2"> <input type="submit" class="btn btn-primary" value="{{ save_txt }}"> </td> </tr>

</table>

</form>

{% endblock %}

survey/templates/survey/survey_list.html
{% extends "survey/base.html" %}
{% load i18n %}

{% block title %}{% trans 'Surveys' %}{% endblock %}
{% block content %}

<table class="table">
  <thead>
    <tr>
      <th> {% trans 'Survey' %} </th>
      <th class="text-right"> {% trans 'Questions' %} </th>
    </tr>
  </thead>
  <tbody>
{% for survey in survey_list %}
    <tr>
      <td title="{{ survey.description|striptags }}">
        <a href="{% url 'survey_detail' survey.name %}"> {{ survey.title }} </a>
      </td>
      <td class="text-right"> {{ survey.questions.count }} </td>
    </tr>
{% endfor %}
  </tbody>
</table>

{% endblock content %}